<!-- sidebar right -->
<a href=""><spring:message code='TranslateDetails_t'/></a>
<c:if test="${!empty model.user}"><a href="" rel="nofollow"><spring:message code='SaveToMyEuropeana_t'/></a></c:if>
<a href="${model.embedRecordUrl}" target="_blank" rel="nofollow"><spring:message code='embed_t'/></a>
<a href="" title="<spring:message code='AltCiteInfo_t' />" rel="nofollow"><spring:message code='Cite_Button_t' /></a>
<c:if test="${!empty model.user}">
<form>  
	<fieldset>
		<label for="add-tag" class="bold"><spring:message code='AddATag_t'/></label><br/>
		<input type="text" id="item-tag" maxlength="50"/>
		<input type="submit" class="submit-button" value="<spring:message code='Add_t'/>"/>
	</fieldset>
</form>
</c:if>
<c:if test="${model[fieldsEnrichment][keys]}"><c:set var="keys" value="${model[fieldsEnrichment][keys]}"/></c:if>
<c:if test="${keys} && ${fn:length(keys) > 0}">
<ul>
  <li>    
    <h3><a href=""><spring:message code='AutoGeneratedTags_t'/></a></h3>
    <ul>
      <c:forEach items="${keys}" var="key">
        <li>            
          <h4><a href=""><spring:message code='${key}'/></a></h4>            
          <ul>
            <%-- <@displayEseDataAsHtml model.fieldsEnrichment[key] 'li' false true/>  --%>
            <%@ include file="/WEB-INF/jsp/vanilla/fulldoc/display-ese-data-as-html.jsp" %>     
          </ul>      
        </li>     
      </c:forEach>
    </ul>
  </li>
</ul>
</c:if>
<!-- /sidebar right -->
